adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter another adjective: ")
type_of_bird = input("Enter a type of bird: ")
room_in_a_house = input("Enter a room in a house: ")
verb_past_tense = input("Enter a verb in past tense: ")
verb = input("Enter a verb: ")
relative_name = input("Enter a relative's name: ")
noun = input("Enter a noun: ")
a_liquid = input("Enter a liquid: ")
verb_ending_in_ing = input("Enter a verb ending in -ing: ")
part_of_the_body = input("Enter a part of the body(plural): ")
plural_noun = input("Enter a plural noun: ")
verb_ending_in_ing2 = input("Enter a verb ending in -ing: ")
noun2 = input("Enter a noun: ")


print("It was a " + adjective1 + ", cold November day. ")
print("I woke up to the " + adjective2 + " smell of " + type_of_bird)
print("roasting in the " + room_in_a_house + " downstairs. I " + verb_past_tense)
print("down the stairs to see if I could help " + verb + ". ")
print("My mom said, \"See if " + relative_name + " needs a fresh " + noun + ".\" ")
print("So I carried a tray of glasses full of " + a_liquid)
print("into the " + verb_ending_in_ing + " room. When I got there, ")
print("I couldn't believe my " + part_of_the_body + "! ")
print("There were " + plural_noun + " " + verb_ending_in_ing2 + " on the " + noun2 + "!")